### ISSUE TITLE
Add JSDocs

### ISSUE THREAD

**Issue by sgwilym** [earthstar-project/stone-soup#139]
## What's the problem you want solved?

It would be very helpful for users of the library to have access to comprehensive API docs describing what every class/function does, its parameters, return type etc. I don't think it makes sense to maintain this independently of the library (for instance as documentation on the website), as the library and documentation would get out of sync easily.

## Is there a solution you'd like to recommend?

Using [JSDoc](https://jsdoc.app) to annotate our codebase. Many tools are able to read this annotation (e.g. `deno doc`) or generate HTML from them. Users would be able to access this documentation the way they most prefer, and our website can focus on providing more high-level documentation.

**Comment by cinnamon-bun** [comment]
Our convention has been to write most of the JSDocs in the type and interface definitions, and not in the specific implementations, since we often have several swappable implementations and don't want to duplicate the docs.

For example: write most docs in `src/storage/storage-types.ts` and not as much in specific files like `src/storage/storage-driver-indexeddb.ts`, except for things specific to IndexedDb.

**Comment by sgwilym** [comment]
There's one thing I'm not sure about with that approach: when you try to import `StorageAsync` you won't get the documentation for it displayed in your IDE as it's all on `IStorageAsync`.

**Comment by cinnamon-bun** [comment]
See also #30 "set up Typedoc"

**Comment by sgwilym** [comment]
Done in #144
